# Generated by Django 5.2.17 on 2026-09-26 02:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_beneficios_fidelidade'),
        ('fidelidade', '0005_nivelfidelidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotepontos',
            name='beneficios_aplicados',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='nivelfidelidade',
            name='bonus_pontos_percentual',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='nivelfidelidade',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddConstraint(
            model_name='nivelfidelidade',
            constraint=models.CheckConstraint(condition=models.Q(('bonus_pontos_percentual__gte', 0), ('bonus_pontos_percentual__lte', 100)), name='nivel_bonus_percentual_valido'),
        ),
        migrations.AddConstraint(
            model_name='nivelfidelidade',
            constraint=models.CheckConstraint(condition=models.Q(('desconto_percentual__gte', 0), ('desconto_percentual__lte', 100)), name='nivel_desconto_percentual_valido'),
        ),
    ]
