# Generated by Django 5.2.17 on 2026-09-26 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_usuario_and_more'),
        ('empresas', '0011_configuracaofidelidadeempresa_devolver_pontos_ao_estornar_resgate'),
        ('fidelidade', '0006_beneficios_fidelidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstornoResgate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_externo', models.CharField(max_length=255)),
                ('devolve_pontos_aplicado', models.BooleanField()),
                ('estornado_em', models.DateTimeField(editable=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estornos_resgates', to='clientes.cliente')),
                ('credencial_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estornos_resgates', to='empresas.credencialintegracao')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estornos_resgates', to='empresas.loja')),
                ('resgate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estorno', to='fidelidade.resgate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('loja', 'identificador_externo'), name='estorno_resgate_loja_identificador_unico')],
            },
        ),
    ]
