# Generated by Django 5.2.17 on 2026-09-27 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0007_estornoresgate'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='resgate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='fidelidade.resgate'),
        ),
    ]
