name: Erro
description: Registrar comportamento inesperado
title: "[ERRO] "
body:
  - type: textarea
    id: observado
    attributes:
      label: Comportamento observado
    validations:
      required: true

  - type: textarea
    id: esperado
    attributes:
      label: Comportamento esperado
    validations:
      required: true

  - type: textarea
    id: reproducao
    attributes:
      label: Como reproduzir
    validations:
      required: true

  - type: textarea
    id: impacto
    attributes:
      label: Impacto
      description: O erro bloqueia alguma entrega?
