# Generated by Django 5.2.17 on 2026-09-22 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='empresas.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
