# Generated by Django 5.2.17 on 2026-09-22 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_classificar_membros_existentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='membroempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='membroempresa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros_empresas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='membroempresa',
            constraint=models.UniqueConstraint(fields=('usuario', 'empresa'), name='membro_usuario_empresa_unico'),
        ),
        migrations.AddField(
            model_name='acessoloja',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acessos_membros', to='empresas.loja'),
        ),
        migrations.AddField(
            model_name='acessoloja',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acessos_lojas', to='empresas.membroempresa'),
        ),
        migrations.AddConstraint(
            model_name='acessoloja',
            constraint=models.UniqueConstraint(fields=('membro', 'loja'), name='acesso_membro_loja_unico'),
        ),
    ]
