# Generated by Django 5.2.17 on 2026-09-26 02:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_politica_arredondamento_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofidelidadeempresa',
            name='base_calculo_pontos',
            field=models.CharField(choices=[('BRUTO', 'Valor original da compra'), ('LIQUIDO', 'Valor pago após descontos')], default='BRUTO', max_length=40),
        ),
        migrations.AddField(
            model_name='configuracaofidelidadeempresa',
            name='beneficio_primeira_compra_apos_inatividade',
            field=models.CharField(choices=[('SEM_BENEFICIOS_NIVEL', 'Sem benefícios de nível'), ('COM_BENEFICIOS_NIVEL', 'Com benefícios de nível')], default='SEM_BENEFICIOS_NIVEL', max_length=40),
        ),
        migrations.AddField(
            model_name='configuracaofidelidadeempresa',
            name='bonus_pontos_retorno_percentual',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='configuracaofidelidadeempresa',
            name='desconto_retorno_percentual',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='configuracaofidelidadeempresa',
            name='inatividade_suspende_beneficios_nivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaofidelidadeempresa',
            name='modo_aplicacao_nivel',
            field=models.CharField(choices=[('ANTES_DA_COMPRA', 'Nível anterior à compra'), ('ATINGIDO_NA_COMPRA', 'Nível atingido na compra')], default='ANTES_DA_COMPRA', max_length=40),
        ),
        migrations.AddField(
            model_name='configuracaofidelidadeempresa',
            name='modo_combinacao_descontos_percentuais',
            field=models.CharField(choices=[('ADITIVO', 'Somar descontos'), ('SEQUENCIAL', 'Aplicar sobre o restante')], default='ADITIVO', max_length=40),
        ),
        migrations.AddField(
            model_name='configuracaofidelidadeempresa',
            name='ordem_aplicacao_resgate',
            field=models.CharField(choices=[('ANTES_DOS_DESCONTOS_PERCENTUAIS', 'Resgate antes dos percentuais'), ('DEPOIS_DOS_DESCONTOS_PERCENTUAIS', 'Resgate depois dos percentuais')], default='DEPOIS_DOS_DESCONTOS_PERCENTUAIS', max_length=40),
        ),
        migrations.AddField(
            model_name='configuracaofidelidadeempresa',
            name='promocao_retorno_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='configuracaofidelidadeempresa',
            constraint=models.CheckConstraint(condition=models.Q(('bonus_pontos_retorno_percentual__gte', 0), ('bonus_pontos_retorno_percentual__lte', 100)), name='cfg_bonus_retorno_percentual'),
        ),
        migrations.AddConstraint(
            model_name='configuracaofidelidadeempresa',
            constraint=models.CheckConstraint(condition=models.Q(('desconto_retorno_percentual__gte', 0), ('desconto_retorno_percentual__lte', 100)), name='cfg_desconto_retorno_percentual'),
        ),
        migrations.AddConstraint(
            model_name='configuracaofidelidadeempresa',
            constraint=models.CheckConstraint(condition=models.Q(('beneficio_primeira_compra_apos_inatividade__in', ['SEM_BENEFICIOS_NIVEL', 'COM_BENEFICIOS_NIVEL'])), name='cfg_beneficio_retorno_valido'),
        ),
        migrations.AddConstraint(
            model_name='configuracaofidelidadeempresa',
            constraint=models.CheckConstraint(condition=models.Q(('modo_combinacao_descontos_percentuais__in', ['ADITIVO', 'SEQUENCIAL'])), name='cfg_combinacao_descontos_valida'),
        ),
        migrations.AddConstraint(
            model_name='configuracaofidelidadeempresa',
            constraint=models.CheckConstraint(condition=models.Q(('ordem_aplicacao_resgate__in', ['ANTES_DOS_DESCONTOS_PERCENTUAIS', 'DEPOIS_DOS_DESCONTOS_PERCENTUAIS'])), name='cfg_ordem_resgate_valida'),
        ),
        migrations.AddConstraint(
            model_name='configuracaofidelidadeempresa',
            constraint=models.CheckConstraint(condition=models.Q(('base_calculo_pontos__in', ['BRUTO', 'LIQUIDO'])), name='cfg_base_pontos_valida'),
        ),
        migrations.AddConstraint(
            model_name='configuracaofidelidadeempresa',
            constraint=models.CheckConstraint(condition=models.Q(('modo_aplicacao_nivel__in', ['ANTES_DA_COMPRA', 'ATINGIDO_NA_COMPRA'])), name='cfg_modo_nivel_valido'),
        ),
    ]
