# Generated by Django 5.2.17 on 2026-09-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_beneficios_fidelidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofidelidadeempresa',
            name='devolver_pontos_ao_estornar_resgate',
            field=models.BooleanField(default=True, help_text='Devolve somente pontos ainda válidos; pontos expirados nunca retornam.'),
        ),
    ]
