# Generated by Django 5.2.17 on 2026-09-27 01:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_configuracaofidelidadeempresa_devolver_pontos_ao_estornar_resgate'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofidelidadeempresa',
            name='limite_resgate_percentual',
            field=models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddConstraint(
            model_name='configuracaofidelidadeempresa',
            constraint=models.CheckConstraint(condition=models.Q(('limite_resgate_percentual__gte', 0), ('limite_resgate_percentual__lte', 100)), name='cfg_limite_resgate_percentual'),
        ),
    ]
