# Generated by Django 5.2.17 on 2026-09-27 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_configuracaofidelidadeempresa_limite_resgate_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofidelidadeempresa',
            name='periodo_recompra_dias',
            field=models.PositiveIntegerField(default=180, help_text='Janela em dias para avaliar a recompra dos clientes da empresa.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='configuracaofidelidadeempresa',
            constraint=models.CheckConstraint(condition=models.Q(('periodo_recompra_dias__gt', 0)), name='cfg_empresa_recompra_positiva'),
        ),
    ]
